export const PRODUCT_REQUEST ="ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS ="ADD_PRODUCT__SUCCESS"
export const PRODUCT_FAILURE ="ADD_PRODUCT__FAILURE"


//GET

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"


export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"